### PR TITLE
Update bob.md to add more direct link to OpenJDK 11 installers

### PR DESCRIPTION
**Pull request by subsoap**

### CODE REVIEW

**Comment by subsoap** [comment]
Also removed mention of old download site.

**Review by britzl — CHANGES_REQUESTED** [review]
I think we should recommend the same installer download page as we have in the GitHub setup instructions:

* https://github.com/defold/defold/blob/dev/README_SETUP_MACOS.md
* https://jdk.java.net/archive/

**Comment by subsoap** [comment]
> I think we should recommend the same installer download page as we have in the GitHub setup instructions:
> 
> * https://github.com/defold/defold/blob/dev/README_SETUP_MACOS.md
> * https://jdk.java.net/archive/

The Microsoft ones are better because they are maintained for security issues while these ones are not. I tested the Microsoft one with bundling with bob and it worked fine. The other doc should have its link changed to match instead.

**Comment by britzl** [comment]
@subsoap I agree. We should recommend the newer ones! Could you please also add this as an alternative download source for JDK11 builds:

https://github.com/adoptium/temurin11-binaries/releases

**Comment by CocosGames** [comment]
Please merge it.

**Review by britzl — APPROVED** [review]
Thank you

**Pull request merged**
