### PR TITLE
fix zh glossary noun error in ParticleFX

### PR DESCRIPTION
**Pull request by ExMikuPro**
#405

### CODE REVIEW

**Comment by CocosGames** [comment]
很高兴有人对中文教程感兴趣.

**Comment by britzl** [comment]
> 很高兴有人对中文教程感兴趣.

@CocosGames is the fix grammatically correct?

**Comment by ExMikuPro** [comment]
> > 很高兴有人对中文教程感兴趣.
> 
> @CocosGames is the fix grammatically correct?

no,Corrected Chinese homonym typos :D

**Comment by CocosGames** [comment]
> > > 很高兴有人对中文教程感兴趣.
> > 
> > 
> > @CocosGames is the fix grammatically correct?
> 
> no,Corrected Chinese homonym typos :D

That's true. @britzl

**Pull request merged**
