### PR TITLE
Greek manuals

### PR DESCRIPTION
**Pull request by ElpidoforosGkikas**
Greek manuals

### CODE REVIEW

**Comment by ElpidoforosGkikas** [comment]
greek manuals

**Comment by britzl** [comment]
Thank you for the contribution! Could you please translate introduction.md as per the instructions in this repo? https://github.com/defold/doc#information-for-translators

**Comment by ElpidoforosGkikas** [comment]
ok i will do this now

**Comment by ElpidoforosGkikas** [comment]
I make the translation of introduction and building blocks
but doesnot let me do pull request
also I fix a small error at addressing.md. thanks

**Comment by britzl** [comment]
> but doesnot let me do pull request

But this is a pull request! You've already created one! :-) I just haven't merged it yet.

**Comment by ElpidoforosGkikas** [comment]
ok you need to merge, after merge I can put the two new translations in another pull request, and has also a fix in addressing thanks

**Comment by britzl** [comment]
You can continue to push new changes to this pull request until I merge it!

**Review by britzl — APPROVED** [review]

**Pull request merged**
