### PR TITLE
PT translation of Introduction.md

### PR DESCRIPTION
**Pull request by FelipeN21**

### CODE REVIEW

**Review by britzl — APPROVED** [review]
Thank you for your contribution!

**Comment by FelipeN21** [comment]
Hey Britzl Could you tag This Pull request as hacktoberfest-accepted so i can get points on the event? Ty

**Comment by FelipeN21** [comment]
> Thank you for your contribution!
Hey Britzl Could you tag This Pull request as hacktoberfest-accepted so i can get points on the event? Ty
PS: If you tag the hole Defold/doc as hacktoberfest it will count for every fulture PR's

**Comment by britzl** [comment]
Sure thing. Done!

**Pull request merged**
