### PR TITLE
Update languages.json

### PR DESCRIPTION
**Pull request by TheUnderName**

### CODE REVIEW

**Comment by britzl** [comment]
@TheUnderName are you planning to start translation of the Defold manuals to Persian?

**Comment by TheUnderName** [comment]
> @TheUnderName are you planning to start translation of the Defold manuals to Persian?
Yes

**Comment by britzl** [comment]
That's great. Please update this PR with translated files and we'll merge them once we have a few of the pages translated.

**Comment by TheUnderName** [comment]
> That's great. Please update this PR with translated files and we'll merge them once we have a few of the pages translated.

Oky

**Comment by britzl** [comment]
There is no need to close. the PR if you intend to submit translations?

**Pull request closed without merging**
