### PR TITLE
Update manual w.r.t. new Open Web Profiler option

### PR DESCRIPTION
**Pull request by vlaaad**
Probably shouldn't merge immediately, and instead wait until it's in stable

### CODE REVIEW

**Comment by vlaaad** [comment]
Why?

**Comment by AGulev** [comment]
Sometimes I have two targets and I wanna compare profiler results for them. 
New menu item open only

**Comment by vlaaad** [comment]
Makes sense, reverted.

**Comment by britzl** [comment]
I've built and published the new docs.

**Pull request merged**
